name: "Docker build & push OnTop"

on:
  workflow_call:
    inputs:
      base_docker_image_version:
        description: 'Base Docker Image version'
        type: string
        required: true
        default: "1"
      tags:
        description: 'Comma separated tags'
        type: string
        required: true
        default: "latest"
      dockerfile_path:
        description: "Dockerfile path"
        type: string
        required: true
        default: "Dockerfile"
      ref:
        description: "Dockerfile ref or sha"
        type: string
        required: true
        default: "master"
  workflow_dispatch:
    inputs:
      base_docker_image_version:
        description: 'Base Docker Image version'
        type: string
        required: true
        default: "1"
      tags:
        description: 'Comma separated tags'
        type: string
        required: true
        default: "latest"
      dockerfile_path:
        description: "Dockerfile path"
        type: string
        required: true
        default: "Dockerfile"
      ref:
        description: "Dockerfile ref or sha"
        type: string
        required: true
        default: master

env:
  IMAGE_NAME: "ghcr.io/${{ github.repository_owner }}/label-studio"

jobs:
  docker_build_and_push:
    name: "Docker image"
    timeout-minutes: 90
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@cd1afbd7852b7ad7b1b7a9a1b03efebd3b0a1820 # v3.0.0

      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          submodules: 'recursive'
          ref: ${{ inputs.ref }}
          fetch-depth: 0

      - name: Calculate Docker tags
        id: calculate-docker-tags
        uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7
        env:
          TAGS: ${{ inputs.tags }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
        with:
          script: |
            const raw_tags_input = process.env.TAGS;
            const image_name = process.env.IMAGE_NAME;
            
            const tags = raw_tags_input.split(',').map(x => x.trim());
            const docker_tags = tags.map(x => `${image_name}:${x}`).join(',');
            console.log(docker_tags);
            core.setOutput("docker-tags", docker_tags);

      - name: Edit Dockerfile
        env:
          BASE_DOCKER_IMAGE_VERSION: ${{ inputs.base_docker_image_version }}
          DOCKERFILE_PATH: ${{ inputs.dockerfile_path }}
        run: |
          sed -i "s#^FROM .*#FROM ${IMAGE_NAME}:${BASE_DOCKER_IMAGE_VERSION}#g" "${DOCKERFILE_PATH}"
          cat "${DOCKERFILE_PATH}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 # v3.8.0

      - name: Login to GHCR
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355 # v6.10.0
        id: docker_build_and_push
        with:
          context: .
          file: ${{ inputs.dockerfile_path }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.calculate-docker-tags.outputs.docker-tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
